start_region:
  min_limits:
#    [-0.20 ,-1.6 ,1.4 ,-1.65 ,-1.65 ,0.0]
#    x, y, z, roll, pitch, yaw
    [0.3 ,-0.5 ,0.6 ,1.57 ,1.57 ,0.0]
  max_limits:
#    [0.20, -1.4, 1.6, -1.45, -1.45 ,3.14159265359]
    [0.7, -0.5, 0.6, 1.57, 1.57, 0.0]

# preprocess_planner: ARAStar
preprocess_planner: RRTConnectkConfigDefault