start_region:
  min_limits:
    [0.5, -0.3, 0.85, 0.0, 0.0, -1.5] # Facing Down: 1.570796
  max_limits:
    [1.2, 0.3, 0.85, 0.0, 0.0, 1.5]

regions:
  pick_region:
    min_limits:
      [-0.3, 0.3, 0.85, 0.0, 0.0, 0.5]  # if tool0: -1.570796, 0.0, 0.0
    max_limits:
      [0.3, 0.9, 0.85, 0.0, 0.0, 1.25] # if tool0: -1.570796, 0.0, 0.0
  place_region:
    min_limits:
      [0.6, -0.3, 0.85, 0.0, 0.0, -0.5]  # if tool0: -1.570796, 0.0, -1.570796
    max_limits:
      [1.3, 0.3, 0.85, 0.0, 0.0, 0.5]

# preprocess_planner: ARAStar
preprocess_planner: RRTConnect # ConfigDefault