start_region:
  min_limits:
#    [0.35, -0.5, 0.3, 0.0, 1.570796, -1.0] # Facing Down
    [0.35, -0.5, 0.3, 0.0, 0.0, -1.0] # Yaw
  max_limits:
    [0.9, 0.5, 0.3, 0.0, 0.0, 1.0]

# preprocess_planner: ARAStar
preprocess_planner: RRTConnect # ConfigDefault